In [14]:
from tensorflow.keras.preprocessing.text import one_hot


In [15]:
# sentences:
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good'      
      ]

In [16]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [17]:
# define vocabulary size
voc_size=10000

# one hot representation
onehot_repr=[one_hot(words,voc_size)for words in sent]
onehot_repr

[[6357, 7838, 9410, 869],
 [6357, 7838, 9410, 4168],
 [6357, 7855, 9410, 2448],
 [230, 2213, 2380, 1151],
 [230, 2213, 3892, 2380, 7040],
 [6963, 6357, 6285, 9410, 8259],
 [2815, 3691, 6297, 2380]]

In [18]:
# word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [19]:
# define the length of the sentence
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6357 7838 9410  869]
 [   0    0    0    0 6357 7838 9410 4168]
 [   0    0    0    0 6357 7855 9410 2448]
 [   0    0    0    0  230 2213 2380 1151]
 [   0    0    0  230 2213 3892 2380 7040]
 [   0    0    0 6963 6357 6285 9410 8259]
 [   0    0    0    0 2815 3691 6297 2380]]


In [20]:
# feature dimension
dim=10


In [21]:
# embedding layer
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')


In [22]:
# model summary
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 636ms/step


array([[[-0.00307085, -0.02295141,  0.01117193,  0.04414897,
         -0.03411265,  0.02570951,  0.00748577,  0.03191913,
         -0.0096962 ,  0.02961827],
        [-0.00307085, -0.02295141,  0.01117193,  0.04414897,
         -0.03411265,  0.02570951,  0.00748577,  0.03191913,
         -0.0096962 ,  0.02961827],
        [-0.00307085, -0.02295141,  0.01117193,  0.04414897,
         -0.03411265,  0.02570951,  0.00748577,  0.03191913,
         -0.0096962 ,  0.02961827],
        [-0.00307085, -0.02295141,  0.01117193,  0.04414897,
         -0.03411265,  0.02570951,  0.00748577,  0.03191913,
         -0.0096962 ,  0.02961827],
        [ 0.00841845, -0.03635637,  0.00916451, -0.02852789,
          0.015668  , -0.04459064,  0.01908142, -0.01502778,
         -0.02552022,  0.03777737],
        [-0.04846615, -0.01210154,  0.04958388,  0.03296847,
          0.03598208,  0.03287354,  0.04207095, -0.03565781,
          0.0359644 , -0.02624872],
        [-0.04549194,  0.03675352,  0.00411621, -0.0